//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP0201
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=connection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arenda> Arenda { get; set; }
        public virtual DbSet<Arendatory> Arendatory { get; set; }
        public virtual DbSet<Employers> Employers { get; set; }
        public virtual DbSet<Pavils> Pavils { get; set; }
        public virtual DbSet<TC> TC { get; set; }
    
        public virtual ObjectResult<ViewTC_Result> ViewTC(string nameTC)
        {
            var nameTCParameter = nameTC != null ?
                new ObjectParameter("nameTC", nameTC) :
                new ObjectParameter("nameTC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewTC_Result>("ViewTC", nameTCParameter);
        }
    }
}
