//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP0201
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavils
    {
        public string Name { get; set; }
        public string NumberOfPavil { get; set; }
        public int Stage { get; set; }
        public string Status { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> PriceForMetr { get; set; }
        public Nullable<double> Koef { get; set; }
    
        public virtual TC TC { get; set; }
    }
}
