//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP0201
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavils
    {
        public string Name { get; set; }
        public string NumberOfPavil { get; set; }
        public int Stage { get; set; }
        public string Status { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> PriceForMetr { get; set; }
        public Nullable<double> Koef { get; set; }
    
        public virtual TC TC { get; set; }
    }
}
